"""ChecklistTemplate/Item/RecurrenceRule (not synced) and
ChecklistRun/RunItem/RunItemTick (synced). See docs/04-design.md §1.2.
Runs are generated by checklists/generator.py; their status changes only
through checklists/runs.py.
"""

from __future__ import annotations

import zoneinfo
from datetime import datetime, timedelta

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Case, Count, Exists, OuterRef, Q, Value, When
from django.db.models.functions import Now, TruncDate
from django.utils import timezone

from organisations.tenancy import SyncedTenantModel, TenantModel, TenantScopedManager


class ChecklistTemplate(TenantModel):
    name = models.CharField(max_length=120)
    location = models.ForeignKey(
        "organisations.Location", on_delete=models.PROTECT, related_name="checklist_templates"
    )
    shift = models.ForeignKey(
        "organisations.Shift",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="checklist_templates",
    )
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        "organisations.Membership",
        on_delete=models.PROTECT,
        related_name="created_checklist_templates",
    )

    class Meta(TenantModel.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=["organisation", "location", "name"],
                name="uniq_checklisttemplate_org_loc_name",
            ),
        ]

    def __str__(self) -> str:
        return self.name


class ChecklistItem(TenantModel):
    template = models.ForeignKey(ChecklistTemplate, on_delete=models.CASCADE, related_name="items")
    order = models.PositiveSmallIntegerField()
    label = models.CharField(max_length=160)
    photo_required = models.BooleanField(default=False)
    skippable = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    class Meta(TenantModel.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=["template", "order"],
                name="uniq_checklistitem_template_order",
                deferrable=models.Deferrable.DEFERRED,
            ),
        ]
        ordering = ["order"]

    def __str__(self) -> str:
        return f"{self.order}. {self.label}"


class RecurrenceKind(models.TextChoices):
    DAILY = "daily", "Daily"
    WEEKLY = "weekly", "Weekly"
    SHIFT_START = "shift_start", "At shift start"


class RecurrenceRule(TenantModel):
    template = models.ForeignKey(
        ChecklistTemplate, on_delete=models.CASCADE, related_name="recurrence_rules"
    )
    kind = models.CharField(max_length=20, choices=RecurrenceKind.choices)
    times = ArrayField(models.TimeField(), default=list, blank=True)
    weekdays = ArrayField(
        models.PositiveSmallIntegerField(), default=list, blank=True, help_text="0 = Mon"
    )
    available_before_min = models.PositiveSmallIntegerField(default=0)
    due_offset_min = models.PositiveSmallIntegerField(default=60)
    starts_on = models.DateField()
    ends_on = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta(TenantModel.Meta):
        constraints = [
            models.CheckConstraint(
                condition=~models.Q(kind=RecurrenceKind.WEEKLY) | models.Q(weekdays__len__gt=0),
                name="chk_recurrencerule_weekly_has_weekdays",
            ),
            models.CheckConstraint(
                condition=models.Q(kind=RecurrenceKind.SHIFT_START) | models.Q(times__len__gt=0),
                name="chk_recurrencerule_needs_times",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.template} ({self.kind})"


class ChecklistRunStatus(models.TextChoices):
    PENDING = "pending", "Pending"
    IN_PROGRESS = "in_progress", "In progress"
    DONE = "done", "Done"
    FLAGGED = "flagged", "Flagged"
    CANCELLED = "cancelled", "Cancelled"


OPEN_RUN_STATUSES = (ChecklistRunStatus.PENDING, ChecklistRunStatus.IN_PROGRESS)


class ChecklistRunQuerySet(models.QuerySet):
    def annotate_overdue(self) -> ChecklistRunQuerySet:
        """Derived, like tasks (ADR-17, docs/04-design.md §5.4)."""
        return self.annotate(
            is_overdue=Case(
                When(status__in=OPEN_RUN_STATUSES, due_at__lt=Now(), then=Value(True)),
                default=Value(False),
                output_field=models.BooleanField(),
            )
        )

    def with_progress(self) -> ChecklistRunQuerySet:
        """item_count and resolved_count (ticked or skipped) for "4 / 9"."""
        return self.annotate(
            item_count=Count("items", distinct=True),
            resolved_count=Count("items", filter=Q(items__ticks__isnull=False), distinct=True),
        )

    def mine(self, membership) -> ChecklistRunQuerySet:
        """A shift run: rostered on that shift on its shift date. A location
        run: rostered on any shift at that location on the run's local day."""
        from organisations.models import ShiftAssignment

        tz = zoneinfo.ZoneInfo(membership.organisation.timezone)
        on_shift = ShiftAssignment.objects.filter(
            membership=membership, shift=OuterRef("shift"), date=OuterRef("shift_date")
        )
        at_location = ShiftAssignment.objects.filter(
            membership=membership,
            shift__location=OuterRef("location"),
            date=OuterRef("local_start_date"),
        )
        return self.annotate(local_start_date=TruncDate("occurrence_start", tzinfo=tz)).filter(
            (Q(shift__isnull=False) & Q(Exists(on_shift)))
            | (Q(shift__isnull=True) & Q(Exists(at_location)))
        )

    def visible_to(self, membership) -> ChecklistRunQuerySet:
        """Same scopes as Task.objects.visible_to (docs/04-design.md §2)."""
        from organisations.permissions import location_scope

        scope = location_scope(membership)
        if scope is None:
            return self
        if not scope:
            return self.mine(membership)
        mine_ids = self.model.objects.mine(membership).values("id")
        return self.filter(Q(location_id__in=scope) | Q(id__in=mine_ids))


class ChecklistRun(SyncedTenantModel):
    template = models.ForeignKey(ChecklistTemplate, on_delete=models.PROTECT, related_name="runs")
    rule = models.ForeignKey(
        RecurrenceRule, on_delete=models.SET_NULL, null=True, blank=True, related_name="runs"
    )
    name = models.CharField(max_length=120)
    location = models.ForeignKey(
        "organisations.Location", on_delete=models.PROTECT, related_name="checklist_runs"
    )
    shift = models.ForeignKey(
        "organisations.Shift",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="checklist_runs",
    )
    shift_date = models.DateField(null=True, blank=True)
    occurrence_start = models.DateTimeField()
    due_at = models.DateTimeField()
    status = models.CharField(
        max_length=20, choices=ChecklistRunStatus.choices, default=ChecklistRunStatus.PENDING
    )
    completed_at_trusted = models.DateTimeField(null=True, blank=True)

    objects = TenantScopedManager.from_queryset(ChecklistRunQuerySet)()

    class Meta(SyncedTenantModel.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=["rule", "occurrence_start"], name="uniq_checklistrun_rule_occurrence"
            ),
        ]
        indexes = [
            models.Index(
                fields=["organisation", "status", "due_at"], name="idx_run_org_status_due"
            ),
            models.Index(fields=["organisation", "location", "due_at"], name="idx_run_org_loc_due"),
            models.Index(fields=["organisation", "updated_seq"], name="idx_run_org_seq"),
        ]

    def __str__(self) -> str:
        return self.name

    @property
    def is_overdue(self) -> bool:
        annotated = self.__dict__.get("_is_overdue_annotation")
        if annotated is not None:
            return annotated
        return self.status in OPEN_RUN_STATUSES and self.due_at < timezone.now()

    @is_overdue.setter
    def is_overdue(self, value: bool) -> None:
        self.__dict__["_is_overdue_annotation"] = value

    @property
    def available_from(self) -> datetime:
        """Items can't be ticked before this (the rule's "available before"
        lead time ahead of the occurrence)."""
        lead = self.rule.available_before_min if self.rule_id else 0
        return self.occurrence_start - timedelta(minutes=lead)


class ChecklistRunItem(SyncedTenantModel):
    """Copied from ChecklistItem when the run is generated."""

    run = models.ForeignKey(ChecklistRun, on_delete=models.CASCADE, related_name="items")
    order = models.PositiveSmallIntegerField()
    label = models.CharField(max_length=160)
    photo_required = models.BooleanField(default=False)
    skippable = models.BooleanField(default=True)

    class Meta(SyncedTenantModel.Meta):
        constraints = [
            models.UniqueConstraint(fields=["run", "order"], name="uniq_runitem_run_order"),
        ]
        indexes = [
            models.Index(fields=["organisation", "updated_seq"], name="idx_runitem_org_seq"),
        ]
        ordering = ["order"]

    def __str__(self) -> str:
        return f"{self.order}. {self.label}"


class ChecklistRunItemTick(SyncedTenantModel):
    """Append-only: the effective tick for an item is the one with the
    earliest `trusted_time`."""

    run_item = models.ForeignKey(ChecklistRunItem, on_delete=models.CASCADE, related_name="ticks")
    membership = models.ForeignKey(
        "organisations.Membership", on_delete=models.PROTECT, related_name="run_item_ticks"
    )
    skipped = models.BooleanField(default=False)
    skip_reason = models.CharField(max_length=200, blank=True)
    photo = models.ForeignKey(
        "tasks.TaskPhoto",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="run_item_ticks",
    )
    device_time = models.DateTimeField()
    trusted_time = models.DateTimeField()

    class Meta(SyncedTenantModel.Meta):
        indexes = [
            models.Index(
                fields=["organisation", "run_item", "trusted_time"],
                name="idx_runitemtick_org_item_time",
            ),
            models.Index(fields=["organisation", "updated_seq"], name="idx_runitemtick_org_seq"),
        ]
        ordering = ["trusted_time"]

    def __str__(self) -> str:
        return f"tick on {self.run_item} by {self.membership}"
