# Generated by Django 5.2.17 on 2026-09-28 13:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSyncLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("device_id", models.UUIDField()),
                ("kind", models.CharField(max_length=30)),
                ("device_time", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=40)),
                ("result_json", models.JSONField()),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
                "indexes": [
                    models.Index(
                        fields=["organisation", "received_at"],
                        name="idx_syncoplog_org_received",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
