# Generated by Django 5.2.17 on 2026-10-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, help_text="Optional email for login"
            ),
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX idx_user_email ON accounts_user(email) WHERE email IS NOT NULL",
            "DROP INDEX idx_user_email",
        ),
    ]
