# Generated by Django 5.2.17 on 2026-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_email_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Optional email for login (in addition to phone)",
                max_length=254,
                null=True,
            ),
        ),
    ]
