# Generated by Django 5.2.17 on 2026-09-28 13:50

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

from organisations.migrations_utils import install_seq_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checklists", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("assignee_location", models.BooleanField(default=False)),
                ("shift_date", models.DateField(blank=True, null=True)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("flagged", "Flagged"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("photo_required", models.BooleanField(default=True)),
                (
                    "reminder_lead_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("completed_at_device", models.DateTimeField(blank=True, null=True)),
                ("completed_at_trusted", models.DateTimeField(blank=True, null=True)),
                ("completed_received_at", models.DateTimeField(blank=True, null=True)),
                ("due_at_when_completed", models.DateTimeField(blank=True, null=True)),
                ("time_untrusted", models.BooleanField(default=False)),
                ("photo_pending", models.BooleanField(default=False)),
                (
                    "flag_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("problem", "Problem"),
                            ("rejected", "Rejected"),
                            ("completed_after_cancel", "Completed after cancel"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("flag_reason", models.CharField(blank=True, max_length=300)),
                ("flag_resolved_note", models.CharField(blank=True, max_length=300)),
                (
                    "assignee_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to="organisations.membership",
                    ),
                ),
                (
                    "assignee_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to="organisations.shift",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_tasks",
                        to="organisations.membership",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_tasks",
                        to="organisations.membership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to="organisations.membership",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_tasks",
                        to="organisations.membership",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="organisations.location",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_tasks",
                        to="organisations.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaskPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.CharField(max_length=200)),
                ("thumb", models.CharField(max_length=200)),
                ("bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("width", models.PositiveSmallIntegerField()),
                ("height", models.PositiveSmallIntegerField()),
                ("taken_at_device", models.DateTimeField(blank=True, null=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checklist_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="checklists.checklistrun",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_photos",
                        to="organisations.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("body", models.CharField(max_length=500)),
                ("is_flag", models.BooleanField(default=False)),
                ("device_time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_comments",
                        to="organisations.membership",
                    ),
                ),
                (
                    "checklist_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="checklists.checklistrun",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hidden_comments",
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="tasks.taskphoto",
                    ),
                ),
            ],
            options={
                "ordering": ["device_time", "created_at"],
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organisation", "status", "due_at"],
                name="idx_task_org_status_due",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organisation", "location", "due_at"],
                name="idx_task_org_loc_due",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organisation", "assignee_membership", "due_at"],
                name="idx_task_org_assignee_due",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organisation", "assignee_shift", "shift_date"],
                name="idx_task_org_shift_date",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_task_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assignee_membership__isnull", False),
                        models.Q(("assignee_shift__isnull", False), _negated=True),
                        models.Q(("assignee_location", True), _negated=True),
                    ),
                    models.Q(
                        models.Q(("assignee_membership__isnull", False), _negated=True),
                        ("assignee_shift__isnull", False),
                        models.Q(("assignee_location", True), _negated=True),
                    ),
                    models.Q(
                        models.Q(("assignee_membership__isnull", False), _negated=True),
                        models.Q(("assignee_shift__isnull", False), _negated=True),
                        ("assignee_location", True),
                    ),
                    _connector="OR",
                ),
                name="chk_task_exactly_one_assignee",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assignee_shift__isnull", True),
                    ("shift_date__isnull", False),
                    _connector="OR",
                ),
                name="chk_task_shift_date_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "flagged"), _negated=True),
                    ("flag_kind__isnull", False),
                    _connector="OR",
                ),
                name="chk_task_flagged_has_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="taskphoto",
            index=models.Index(
                fields=["organisation", "task"], name="idx_taskphoto_org_task"
            ),
        ),
        migrations.AddIndex(
            model_name="taskphoto",
            index=models.Index(
                fields=["organisation", "linked_at"], name="idx_taskphoto_org_linked"
            ),
        ),
        migrations.AddIndex(
            model_name="taskphoto",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_taskphoto_org_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["organisation", "task", "device_time"],
                name="idx_taskcomment_org_task_time",
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["organisation", "checklist_run", "device_time"],
                name="idx_taskcomment_org_run_time",
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_taskcomment_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskcomment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("task__isnull", False), ("checklist_run__isnull", True)),
                    models.Q(("task__isnull", True), ("checklist_run__isnull", False)),
                    _connector="OR",
                ),
                name="chk_taskcomment_exactly_one_parent",
            ),
        ),
        install_seq_trigger("tasks_task"),
        install_seq_trigger("tasks_taskphoto"),
        install_seq_trigger("tasks_taskcomment"),
    ]
