# Generated by Django 5.2.17 on 2026-09-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_cancelled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="photo_pending",
        ),
    ]
