# Generated by Django 5.2.17 on 2026-10-09 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_photo_pending"),
        ("organisations", "0003_memberactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRecurrenceRule",
            fields=[
                ("id", models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organisations.organisation")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_recurrence_rules", to="organisations.membership")),
                ("kind", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("shift_start", "At shift start")], max_length=20)),
                ("times", models.JSONField(default=list, help_text="List of [hours, minutes] or empty for all-day")),
                ("weekdays", models.JSONField(default=list, help_text="List of 0-6 (Mon-Sun), empty for all days")),
                ("available_before_min", models.PositiveSmallIntegerField(null=True, blank=True)),
                ("due_offset_min", models.PositiveSmallIntegerField(default=0)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(null=True, blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Recurrence Rule",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_rule",
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_occurrences", to="tasks.taskrecurrencerule"),
        ),
        migrations.AddField(
            model_name="task",
            name="occurrence_start",
            field=models.DateTimeField(null=True, blank=True, help_text="When this occurrence begins (for recurring tasks)"),
        ),
        migrations.AddConstraint(
            model_name="taskrecurrencerule",
            constraint=models.UniqueConstraint(fields=["organisation", "created_by", "starts_on"], name="unique_rule_per_creator_date"),
        ),
        migrations.AddIndex(
            model_name="taskrecurrencerule",
            index=models.Index(fields=["organisation", "is_active", "starts_on"], name="idx_rule_org_active_start"),
        ),
    ]
