# Generated by Django 5.2.17 on 2026-10-09 04:24

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_memberactivity"),
        ("tasks", "0004_add_recurrence_and_self_tasks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskrecurrencerule",
            options={
                "base_manager_name": "unscoped",
                "verbose_name": "Task Recurrence Rule",
            },
        ),
        migrations.AlterModelManagers(
            name="taskrecurrencerule",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="taskrecurrencerule",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="taskrecurrencerule",
            name="organisation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
    ]
