# Generated by Django 5.2.17 on 2026-09-28 13:50

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import organisations.models
import uuid
from django.conf import settings
from django.db import migrations, models

from organisations.migrations_utils import create_seq_and_function, install_seq_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must run before any install_seq_trigger() call, in this migration
        # or any other app's (docs/04-design.md §1.1).
        create_seq_and_function(),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Kampala",
                        max_length=64,
                        validators=[organisations.models.validate_timezone],
                    ),
                ),
                ("country_code", models.CharField(default="UG", max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("photo_required_default", models.BooleanField(default=True)),
                (
                    "default_reminder_lead_min",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("escalation_delay_min", models.PositiveSmallIntegerField(default=30)),
                ("quiet_hours_start", models.TimeField(default="22:00")),
                ("quiet_hours_end", models.TimeField(default="06:00")),
                ("sms_monthly_cap", models.PositiveIntegerField(default=1000)),
                ("daily_summary_time", models.TimeField(blank=True, null=True)),
                ("photo_retention_days", models.PositiveSmallIntegerField(default=90)),
                (
                    "record_retention_days",
                    models.PositiveSmallIntegerField(default=730),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("supervisor", "Supervisor"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_name", models.CharField(blank=True, max_length=80)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MembershipLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.location",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="memberships",
                through="organisations.MembershipLocation",
                to="organisations.location",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="organisation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="organisation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=40)),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.UUIDField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=60)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        help_text="0 = Mon ... 6 = Sun",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="organisations.location",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_seq", models.BigIntegerField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "date",
                    models.DateField(help_text="The local date the shift starts."),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organisations.shift",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="membershiplocation",
            constraint=models.UniqueConstraint(
                fields=("membership", "location"), name="uniq_membershiplocation"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organisation", "role"], name="idx_membership_org_role"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_membership_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("organisation", "user"), name="uniq_membership_org_user"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_location_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("organisation", "name"), name="uniq_location_org_name"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organisation", "created_at"], name="idx_audit_org_created"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organisation", "target_type", "target_id"],
                name="idx_audit_org_target",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_shift_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("organisation", "location", "name"),
                name="uniq_shift_org_loc_name",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["organisation", "date"], name="idx_shiftassign_org_date"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["organisation", "membership", "date"],
                name="idx_shiftassign_org_mem_date",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_shiftassign_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                fields=("shift", "membership", "date"), name="uniq_shiftassignment"
            ),
        ),
        install_seq_trigger("organisations_location"),
        install_seq_trigger("organisations_membership"),
        install_seq_trigger("organisations_shift"),
        install_seq_trigger("organisations_shiftassignment"),
    ]
