# Generated by Django 5.2.17 on 2026-09-28 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="quiet_hours_end",
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="quiet_hours_start",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
