# Generated by Django 5.2.17 on 2026-09-29 08:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_alter_organisation_quiet_hours_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("notifications_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="organisations.membership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "member activity",
                "abstract": False,
                "base_manager_name": "unscoped",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
