# Generated by Django 5.2.17 on 2026-09-28 13:50

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checklists", "0001_initial"),
        ("organisations", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistrunitemtick",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="run_item_ticks",
                to="tasks.taskphoto",
            ),
        ),
        migrations.AddField(
            model_name="checklistrunitemtick",
            name="run_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticks",
                to="checklists.checklistrunitem",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_checklist_templates",
                to="organisations.membership",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklist_templates",
                to="organisations.location",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="organisation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklist_templates",
                to="organisations.shift",
            ),
        ),
        migrations.AddField(
            model_name="checklistrun",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="checklists.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="checklists.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="recurrencerule",
            name="organisation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="recurrencerule",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_rules",
                to="checklists.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="checklistrun",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="checklists.recurrencerule",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrunitem",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_runitem_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistrunitem",
            constraint=models.UniqueConstraint(
                fields=("run", "order"), name="uniq_runitem_run_order"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrunitemtick",
            index=models.Index(
                fields=["organisation", "run_item", "trusted_time"],
                name="idx_runitemtick_org_item_time",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrunitemtick",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_runitemtick_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.UniqueConstraint(
                fields=("organisation", "location", "name"),
                name="uniq_checklisttemplate_org_loc_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("template", "order"),
                name="uniq_checklistitem_template_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrencerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "weekly"), _negated=True),
                    ("weekdays__len__gt", 0),
                    _connector="OR",
                ),
                name="chk_recurrencerule_weekly_has_weekdays",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurrencerule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "shift_start"), ("times__len__gt", 0), _connector="OR"
                ),
                name="chk_recurrencerule_needs_times",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrun",
            index=models.Index(
                fields=["organisation", "status", "due_at"],
                name="idx_run_org_status_due",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrun",
            index=models.Index(
                fields=["organisation", "location", "due_at"],
                name="idx_run_org_loc_due",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistrun",
            index=models.Index(
                fields=["organisation", "updated_seq"], name="idx_run_org_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistrun",
            constraint=models.UniqueConstraint(
                fields=("rule", "occurrence_start"),
                name="uniq_checklistrun_rule_occurrence",
            ),
        ),
    ]
