# Generated by Django 5.2.17 on 2026-09-28 13:50

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to_e164", models.CharField(max_length=16)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("overdue", "Overdue"),
                            ("escalation", "Escalation"),
                            ("flag", "Flag"),
                            ("rejected", "Rejected"),
                            ("synced_late", "Synced late"),
                            ("daily_summary", "Daily summary"),
                            ("pin_setup", "PIN setup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=20)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("step", models.PositiveSmallIntegerField(default=0)),
                ("body", models.CharField(max_length=160)),
                ("dedupe_key", models.CharField(max_length=120, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("held", "Held"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("send_after", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("provider_message_id", models.CharField(blank=True, max_length=80)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=300)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organisations.membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
                "indexes": [
                    models.Index(
                        fields=["status", "send_after"],
                        name="idx_notification_status_send",
                    ),
                    models.Index(
                        fields=["organisation", "created_at"],
                        name="idx_notification_org_created",
                    ),
                    models.Index(
                        fields=["organisation", "target_type", "target_id"],
                        name="idx_notification_org_target",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SmsUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField(help_text="First day of the month.")),
                ("count", models.PositiveIntegerField(default=0)),
                ("warned_80", models.BooleanField(default=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "unscoped",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "month"), name="uniq_smsusage_org_month"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
