# Generated by Django 5.2.17 on 2026-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reminder", "Reminder"),
                    ("overdue", "Overdue"),
                    ("escalation", "Escalation"),
                    ("flag", "Flag"),
                    ("rejected", "Rejected"),
                    ("synced_late", "Synced late"),
                    ("daily_summary", "Daily summary"),
                    ("pin_setup", "PIN setup"),
                    ("budget_warning", "SMS budget warning"),
                ],
                max_length=20,
            ),
        ),
    ]
